on:
  push:
    branches:
      - '*'

jobs:
  warpd:
    uses: ops42-org/warpd/.github/workflows/warpd.yaml@main
    name: Run Warps

  # warpd:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run Warpd
  #       id: warpd
  #       uses: ops42-org/warpd/github-warpd@main


